development:
  adapter: mysql2
  encoding: utf8
  database: sorcery_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: sorcery_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: sorcery_production
  pool: 5
  username: root
  password:
