# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbbcb91b5dccfb8eec37e87838ed16609f6a7427bc080a21e4ca8ebcbdbabf13be9fbbb7c36eea443a1749aee774594ebf8fbc12316b7418f5bc2c2ef853e902

test:
  secret_key_base: 7119731e8b98313dbe7d42889e9489b45a3fc6b0469cc05b97f99f4df0f9e541a68739e8ab7f65245027839a7fdc6ac292997f93d92a218c8cad54688e76c5f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
